# Generated by Django 3.1 on 2021-10-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
