# Generated by Django 3.1 on 2021-10-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
