# Generated by Django 3.1 on 2021-10-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0006_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
